// You are given two strings s and t.
// String t is generated by random shuffling string s and then add one more letter at a random position.
// Return the letter that was added to t.

// Example 1:
// Input: s = "abcd", t = "abcde"
// Output: "e"
// Explanation: 'e' is the letter that was added.

// Example 2:
// Input: s = "", t = "y"
// Output: "y"

import java.util.HashMap;
import java.util.Map;

public class Find_the_Difference{
    public static char findTheDifference(String s , String t){
        // used Hashmap data Structure : 
        Map<Character, Integer> freq = new HashMap<>();
        // added to hashMap ok : 
        for(char ch : s.toCharArray()){
            freq.put(ch,freq.getOrDefault(ch,0)+1);
        }
        // loop over t : 
        for(char ch : t.toCharArray()){
            if(!freq.containsKey(ch) || freq.get(ch) ==0){
                return ch;
            }
            freq.put(ch,freq.get(ch)-1);
        }
        return ' ';
    }
    public static void main(String[] args) {
        String s = "abcd";
        String t = "abcde";
        char ch = findTheDifference(s, t);
        System.out.println("The difference character is : "+ch);
    }
}
